apiVersion: apps/v1
kind: Deployment
metadata:
  name: z21-gateway-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z21-gateway-main
  template:
    metadata:
      labels:
        app: z21-gateway-main
    spec:
      containers:
        - name: z21-gateway-main
          image: ko://github.com/trains-io/z21-gateway
          env:
            - name: Z21_NAME
              valueFrom:
                configMapKeyRef:
                  name: z21-config
                  key: Z21_NAME
            - name: Z21_ADDR
              valueFrom:
                configMapKeyRef:
                  name: z21-config
                  key: Z21_ADDR
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: z21-config
                  key: NATS_URL
