name: Publish Container Image

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
      -  v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    name: Build & Publish Container Image
    runs-on: ubuntu-latest
    
    env:
      KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/z21-gateway
      KO_IMAGE_TAG: ${{ github.ref_name }}
      GIT_SHA: ${{ github.sha }}
      BUILD_DATE: ${{ github.event.head_commit.timestamp }}
      GOPRIVATE: ${{ github.repository_owner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
    
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install ko
        uses: ko-build/setup-ko@v0.6

      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Image
        run: |
          echo "Building image with ko ..."
          ko build --bare --tags "${KO_IMAGE_TAG}" ./...
